security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CLIENT: ROLE_CLIENT


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                target_path_parameter: go_to
                failure_path_parameter: back_to
                use_referer: true

            logout:       true
            anonymous:    true
            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client_space, role: ROLE_CLIENT }
        
        # - { path: ^/refer_friend, role: ROLE_CLIENT }
        # - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https}
