<?php

namespace ClientBundle\Repository;

/**
 * EchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchangeRepository extends \Doctrine\ORM\EntityRepository
{



public function getsend($user) {
    $sql = 'select e.id as id , e.createdat as createdat ,e.titre as titre, e.file as file, f.name as name  from echanges e , fos_user f where e.id_sender='.$user.' and f.id=e.id_sender ';
$params = array(
);




return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }







public function getstat($id,$date) {
    $sql = 'SELECT count(id) as som FROM `echanges` WHERE DATE_FORMAT(createdat,"%Y-%m-%d") = "'.$date.'" and id_sender = '.$id.'';
$params = array(
);

return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetch();

}


public function getstatadminfile($date) {
    $sql = 'SELECT count(id) as som FROM `echanges` WHERE DATE_FORMAT(createdat,"%Y-%m-%d") = "'.$date.'" ';
$params = array(
);





return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetch();
    }


public function getallfiles() {
    $sql = 'select e.id as id , e.createdat as createdat ,e.titre as titre, e.file as file, f.name as name ,e.description as description  from echanges e , fos_user f where  f.id=e.id_sender ';
$params = array(
);




return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }



    public function getreceived($user) {
    $sql = 'select e.id as id , e.createdat as createdat ,e.titre as titre, e.file as file, f.name as name from echange e ,hasechange h , fos_user f where h.id_doctor='.$user.' and f.id=h.id_doctor group by e.id ';
$params = array(
);




return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
