<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBnixok9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBnixok9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBnixok9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBnixok9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBnixok9\appProdProjectContainer([
    'container.build_hash' => 'Bnixok9',
    'container.build_id' => '0f69fc89',
    'container.build_time' => 1581888611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBnixok9');
