<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLofsc3u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLofsc3u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLofsc3u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLofsc3u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLofsc3u\appDevDebugProjectContainer([
    'container.build_hash' => 'Lofsc3u',
    'container.build_id' => 'b3dd67a4',
    'container.build_time' => 1582855839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLofsc3u');
